Issue 11 otobo in docker
RotherOSS/doc-otobo-installation pull request #21
Opened 2020-09-21 11:22 UTC by bschmalhofer

2020-09-22 16:10 UTC, GritRother-OTOBO requested changes
Hi Bernhard, 

Hope this works. I've added the changed lines as comments now. Not sure about how handy this is though, as it's mostly little things like commas, and I fear you have to do the changes now ... Just let me know if it would be easier if I'd changed the files, and you'd prefer me to do this in the future!

There is just one point where I wasn't quite sure about the meaning. 

Grit

2020-09-23 07:46 UTC, bschmalhofer commented on content/migration-from-otrs-6.rst
> +When the web application OTOBO runs in a container then it can't access directories outside the container.
Here, I added the name of the web container.

2020-09-23 07:57 UTC, bschmalhofer commented on content/migration-from-otrs-6.rst
> +The exception are directories that were mounted as volumes inside the container. This means that for
@GritRother-OTOBO , you understood correctly. For clarification I replaced 'inside' with 'into'.

2020-09-23 07:59 UTC, bschmalhofer commented on content/migration-from-otrs-6.rst
> +    When OTOBO runs inside a Docker container then specify __localhost_ for OTRS server and _/opt/otobo/tmp/otrs_ as the OTRS home directory.
My usual mistake. '_' is used in Github Issues for italics, in rst it's \*.

2020-09-23 08:04 UTC, bschmalhofer commented on content/migration-from-otrs-6.rst
> +When that happens please check the settings in Kernel/Config.pm and changes them back to sane values.
Used 'revert' instead of 'change back'.

2020-09-23 09:17 UTC, bschmalhofer commented on content/migration-from-otrs-6.rst
> +When the web application OTOBO runs in a container then it can't access directories outside the container.
Name of the container is now mentioned first.

2020-09-23 09:18 UTC, merged