Issue rother oss/otobo#514 nginx customized
RotherOSS/doc-otobo-installation pull request #28
Opened 2020-10-05 12:04 UTC by bschmalhofer

This PR needs to be reviewed.

2020-10-05 13:37 UTC, GritRother-OTOBO requested changes
Proofread files. Some minor things to be changed please. Thanks!

2020-10-06 08:18 UTC, bschmalhofer commented on content/installation-docker.rst
> +Docker host or a dedicated user with the required permissions.
done

2020-10-06 08:18 UTC, bschmalhofer commented on content/installation-docker.rst
> +The default OTOBO Docker based installation provides the container `otobo_nginx_1`. This container
done

2020-10-06 08:24 UTC, bschmalhofer commented on content/installation-docker.rst
> +Another supported approach is to provide a customized config template in a volume. In this case we first must create a volume that
Tried to simplify the two sentences. @GritRother-OTOBO , could you have another look?

2020-10-06 08:27 UTC, bschmalhofer commented on content/installation-docker.rst
>  After building one can select the wanted image by setting
done, but used the plural, because multiple images are built

2020-10-06 08:30 UTC, bschmalhofer commented on content/installation-docker.rst
>  Upgrading to a new patchlevel release
root zu docker_admin hatte ich bereits repariert. 'Upgrading' finde ich passender, da auf eine höhere Version aktualisiert wird.

2020-10-06 08:31 UTC, bschmalhofer commented on content/installation-docker.rst
>  The following instructions assume that the requirements are installed and that you have a working Docker environment.
done

2020-10-06 08:32 UTC, bschmalhofer commented on content/installation-docker.rst
>  To verify that the six, or five in the case of HTTP only, services are actually running type:
done

2020-10-06 08:34 UTC, bschmalhofer commented on content/installation-docker.rst
> +There are various possiblilites for customizing the Nginx configuration. One way is to use a locally built
done

2020-10-06 08:55 UTC, bschmalhofer commented on content/installation-docker.rst
> +serves as a reverse proxy that provides HTTPS support for the HTTP based OTOBO web application.
done

2020-10-06 11:46 UTC, GritRother-OTOBO commented on content/installation-docker.rst
>  Upgrading to a new patchlevel release
Hmm ... Jetzt bin ich nicht sicher, ob wir das gleiche meinen. 
Deshalb nochmal zur Klärung:

Bei OTRS (und in unseren Supportverträgen, deshalb sollten wir das so beibehalten) wird zwischen Update (= neueres Release einer Version z. B. von 6.2 auf 6.3) und Upgrade (= neue Version, z. B. 6.5 > 7.0) unterschieden. 
Aus dem Begriff Patch Level Release hatte ich jetzt auf ein neueres Release einer bestehenden Version geschlossen (also z. B. 10.3 > 10.4) und das deshalb als Update bezeichnet.

2020-10-06 11:53 UTC, GritRother-OTOBO commented on content/installation-docker.rst
> +Another supported approach is to provide a customized config template in a volume. In this case we first must create a volume that
@bschmalhofer I don't think I can see your changes here, sorry. In the text above, nginx should be decapitalized and I'd still change what I wanted to change at first place.

2020-10-06 12:48 UTC, bschmalhofer commented on content/installation-docker.rst
> +Another supported approach is to provide a customized config template in a volume. In this case we first must create a volume that
@GritRother-OTOBO  Ich glaube ich hatte meine Änderung nicht gepushed. Hier is die aktuelle Version:
```

There are various possibilites for customizing the nginx configuration. One way is to use a locally built
image that is derived from the image `otobo-nginx-webproxy`. In such a local image, nginx can be configured in a
very flexible way.

Another supported approach is to only override the default config template with a customized version.
In this case, we have to create a volume, that contains the adapted nginx config template, first.

```

2020-10-06 12:53 UTC, bschmalhofer commented on content/installation-docker.rst
> +In order to achieve this uncomment or add the following lines in your *.env* file,
done

2020-10-06 12:56 UTC, bschmalhofer commented on content/installation-docker.rst
> +The changes Docker compose config can be inspected with:
done

2020-10-06 12:58 UTC, bschmalhofer commented on content/installation-docker.rst
>  Upgrading to a new patchlevel release
@GritRother-OTOBO  Die Unterscheidung war mir nicht bewusst. Ich gehe die Datei nochmal durch.

2020-10-06 13:02 UTC, bschmalhofer commented on content/installation-docker.rst
>  Upgrading to a new patchlevel release
done

2020-10-06 13:04 UTC, bschmalhofer commented on content/installation-docker.rst
> +Finally the containers can be restarted:
done

2020-10-06 13:39 UTC, GritRother-OTOBO commented on content/installation-docker.rst
> +Another supported approach is to provide a customized config template in a volume. In this case we first must create a volume that
Das erklärt's ;)

Gut so! Jetzt kann nur im letzten Satz das Komma vor "that" noch weg, dann passt's:
In this case, we have to create a volume that contains the adapted nginx config template, first.

2020-10-06 13:41 UTC, GritRother-OTOBO commented on content/installation-docker.rst
>  Upgrading to a new patchlevel release
@bschmalhofer 
Danke!

2020-10-06 14:19 UTC, merged